service:
- docker
require: sudo
env:
  global:
  - TERM=dumb
language: java
install: true
before_script:
- sudo apt update -y || true >/dev/null 2>&1
- sudo apt install -y --no-install-recommends curl docker-ce python-pip >/dev/null 2>&1
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 80
script:
# maven
- bash ./mvnw clean package com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:up >/dev/null 2>&1
- wait_for 8080
- sleep 35
- docker ps
- http :8080/app/
- bash ./mvnw com.dkanejs.maven.plugins:docker-compose-maven-plugin:1.0.1:down >/dev/null 2>&1
- stop_any 8080 80
# gradle
- bash ./gradlew clean composeUp >/dev/null 2>&1
- wait_for 8080
- docker ps
- http :8080/app/
- bash ./gradlew composeDown >/dev/null 2>&1
- stop_any 8080 80
# gradle maven prfile
- bash ./mvnw
- bash ./gradlew composeUp -Pprofile=maven >/dev/null 2>&1
- wait_for 8080
- docker ps
- http :8080/app/
- bash ./gradlew composeDown >/dev/null 2>&1
- stop_any 8080 80
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
